name: "Read/Write profiles' data"
on: [push]

jobs:
  table:
    runs-on: ubuntu-latest
    name: Update README from json data
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - run: |
          npm i
          node generate.js
      - name: "Read/Write profiles' data"
        uses: EddieHubCommunity/gh-actions-html-table-generator@main
        with:
          json-file-path: ".cache/data.json"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          columns: 3
          file-to-use: "profiles.md"
          object-field-names: '[ "bylickilabs", "Thorsten Bylicki", "https://user-images.githubusercontent.com/109308073/208296882-ea239594-81ea-419f-ae6f-e3470ccc9a3e.png", "#1573" ]'
          html-cell: '<td align="center"><p><a href="https://github.com/{{ username }}">{{ name }}</a></p><img src="{{ image }}" alt="GitHub profile of {{ name }}" /><p><a href="https://github.com/EddieHubCommunity/awesome-github-profiles/issues/{{ issueId }}">(💯 give your vote)</a></p></td>'
