name: Bylickilabs Generate Snake

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:
  
jobs:

  build:
  
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
      - uses: platane/snk@master
        id: snake-gif
        
        with:
          github_user_name: bylickilabs
          svg_out_path: ©bylickilabs/github-contribution-grid-snake.svg
          
      - run: git status
      - name: Push changes
        uses: ad-m/github-push-action@master
        
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
          
      - uses: crazy-max/ghaction-github-pages@v3
      
        with:
          target_branch: bylickilabs
          build_dir: ©bylickilabs
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
